apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-api-config
data:
  ENVIRONMENT: production
  LOG_LEVEL: INFO
  QDRANT_COLLECTION: candidate_embeddings
  QDRANT_JOB_COLLECTION: job_description_embeddings
